### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by dandxy89** [deeplearning4j/ScalNet#13]
Are @turambar and @agibsonccc (deeplearning4j) planning any more updates to this repository?

**Comment by agibsonccc** [comment]
Yes. Dave just isn't in the habit of pushing things till they're done..

**Comment by turambar** [comment]
@dandxy89 @agibsonccc We certainly are, but for the moment, I've been working on complementary functionality, e.g., importing keras model configurations and weights. Expect an update to this repos in the next week, though.

**Comment by dandxy89** [comment]
@turambar thanks for the update. I wasn't in any rush for any commits, just wanted to know that development had not stopped. 

I'm currently still in the process of learning Scala so would only contribute examples to the repository. The longer term goal would be to use this as part of deployments with our clients, until then, it will remain a personal endeavour.
