### ISSUE TITLE
Unable to use ScalNet 0.7.0 with SBT.

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/ScalNet#15]
If I add `libraryDependencies += "org.deeplearning4j" % "scalnet_2.11" % "0.7.0"` to a project with `scalaVersion := "2.11.8"` SBT reports that there are unresolved dependencies.

The full SBT log points to a possibly mis-configured POM file.

I am able to use 0.6.0 with no problems.

[sbt.last.log.txt](https://github.com/deeplearning4j/ScalNet/files/619153/sbt.last.log.txt)

**Comment by wmeddie** [comment]
You should be able to use `sbt new wmeddie/dl4j-scalnet.g8` and change the scalnet version to reproduce the exact error I'm seeing.

**Comment by huitseeker** [comment]
Hi @wmeddie, thanks for reporting this one. The reason for this is that artefactids using this are produced from https://github.com/deeplearning4j/ScalNet/pull/10 using a subsitututed artifactid (with a `_2.10`, `_2.11` suffix) that is seemingly not replaced in the shipping POM (though it is in the build). We'll fix this one with a revert, a `change_scala_version.sh` script (and possibly https://github.com/deeplearning4j/ScalNet/pull/11).
