### ISSUE TITLE
Any document or example for this project?

### ISSUE THREAD

**Issue by ztaoo** [deeplearning4j/ScalNet#28]
i don't know where to start.

**Comment by maxpumperla** [comment]
@ztaoo try one of the examples, e.g.

https://github.com/deeplearning4j/ScalNet/blob/master/src/test/scala/org/deeplearning4j/scalnet/examples/keras/feedforward/MLPMnistTwoLayerExample.scala

**Comment by ztaoo** [comment]
thx, @maxpumperla .
This is what i am looking for.

**Comment by maxpumperla** [comment]
cool, glad I could help. have fun with the project!
