### ISSUE TITLE
NeuralNet.scala  "fit" method ignore "nbEpoch" parameter.

### ISSUE THREAD

**Issue by ztaoo** [deeplearning4j/ScalNet#29]
#### Issue Description
```
org.deeplearning4j.scalnet.models.NeuralNet

  override def fit(iter: DataSetIterator, nbEpoch: Int = 10, listeners: List[IterationListener]): Unit = {
    model.setListeners(listeners.asJavaCollection)
    for (epoch <- 0 until nbEpoch)
      println("Epoch " + epoch)
      model.fit(iter)
  }
```
https://github.com/deeplearning4j/ScalNet/blob/master/src/main/scala/org/deeplearning4j/scalnet/models/NeuralNet.scala

fix:
```
  override def fit(iter: DataSetIterator, nbEpoch: Int = 10, listeners: List[IterationListener]): Unit = {
    model.setListeners(listeners.asJavaCollection)
    for (epoch <- 0 until nbEpoch) {
      println("Epoch " + epoch)
      model.fit(iter)
    }
  }
```
it should be like this?

#### Version Information
"org.deeplearning4j" %% "scalnet" % "0.8.0"

#### Contributing
I do not have any experience.
but I would like to contribute if any chance.

**Comment by maxpumperla** [comment]
good catch, your fix is valid. Mind opening a PR?

**Comment by ztaoo** [comment]
@maxpumperla , I will try.

**Comment by ztaoo** [comment]
@maxpumperla .
I use sbt everyday, but I have never use maven before.

I can not test the project, error:
```
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.deeplearning4j/deeplearning4j-core/0.8.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/deeplearning4j/deeplearning4j-core/0.8.1-SNAPSHOT/deeplearning4j-core-0.8.1-SNAPSHOT.pom
[info] Resolving org.nd4j#nd4j-native;0.8.1-SNAPSHOT ...
[warn]  module not found: org.nd4j#nd4j-native;0.8.1-SNAPSHOT
[warn] ==== local: tried
[warn]   C:\Users\Tao\.ivy2\local\org.nd4j\nd4j-native\0.8.1-SNAPSHOT\ivys\ivy.xml
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.nd4j/nd4j-native/0.8.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/nd4j/nd4j-native/0.8.1-SNAPSHOT/nd4j-native-0.8.1-SNAPSHOT.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.deeplearning4j#deeplearning4j-core;0.8.1-SNAPSHOT: not found
[warn]  :: org.nd4j#nd4j-native;0.8.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.deeplearning4j:deeplearning4j-core:0.8.1-SNAPSHOT ((com.typesafe.sbt.pom.MavenHelper) MavenHelper.scala#L84)
[warn]            +- org.deeplearning4j:scalnet_2.11:0.8.1-SNAPSHOT
[warn]          org.nd4j:nd4j-native:0.8.1-SNAPSHOT ((com.typesafe.sbt.pom.MavenHelper) MavenHelper.scala#L84)
[warn]            +- org.deeplearning4j:scalnet_2.11:0.8.1-SNAPSHOT
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.deeplearning4j#deeplearning4j-core;0.8.1-SNAPSHOT: not found
[error] unresolved dependency: org.nd4j#nd4j-native;0.8.1-SNAPSHOT: not found

```

Maybe network issue, maybe maven issue, I am not sure.

fixing this issue is easy, but test is too hard for me.
Would you please fix this issue?

**Comment by saudet** [comment]
> @saudet
> I have tried to make some contribution to this repos( issue #29), but failed.
> I will keep trying but not for sure if I can solve the problem.

What do you mean? Are you having problems creating a pull request?

**Comment by maxpumperla** [comment]
@ztaoo it says above that it can't find the respective snapshots of dl4j and nd4j. How do you run this? `mvn clean test`?

If you're interested, here's how to build stuff locally:

https://deeplearning4j.org/buildinglocally

Otherwise, of course we can do this fix as well. Thought you might be interested in contributing. Thanks in any case.

**Comment by huitseeker** [comment]
1. the user seems to have no problem creating a PR, but building
2. the issue seems to be solved here: https://github.com/deeplearning4j/nd4j/issues/1850

**Comment by ztaoo** [comment]
@saudet ,  I have problems building the project, as @huitseeker said.
so i am not sure whether i can do some contribution.

@maxpumperla , 
I use sbt to run the test, not maven.
Maybe i should learn how to use maven first?
I am interest in contributing, but learning maven or other related problems may cost to much time.

@huitseeker 
thank you. i will check the issue you mentioned.

**Comment by ztaoo** [comment]
#https://github.com/sbt/sbt/issues/3304

**Comment by maxpumperla** [comment]
this has been resolved on master
