### ISSUE TITLE
A bug on LenetMnistExample

### ISSUE THREAD

**Issue by marker68** [deeplearning4j/ScalNet#5]
Got the following error when building ScalNet for scala 2.11, MacOSX 10.11:

```
[ERROR] /Users/tuannguyen/Develop/projects/github/ScalNet/src/test/scala/org/deeplearning4s/mnist/example/LeNetMnistExample.scala:28: error: object NeuralNet is not a member of package org.deeplearning4s.models
[INFO] import org.deeplearning4s.models.{NeuralNet, Sequential}
```

Just removed the NeuralNet part to get it works, but not sure if it is OK or not.
Full build log: 
[build.txt](https://github.com/deeplearning4j/ScalNet/files/457258/build.txt)

**Comment by turambar** [comment]
Fixed. Had a stray import.
