### ISSUE TITLE
Problem loading Snapshot

### ISSUE THREAD

**Issue by ymihere** [deeplearning4j/ScalNet#7]
Hi,

after importing into IntelliJ I get the errors ...

    Dependency '''org.nd4j:nd4j-native:0.5.1-SNAPSHOT''' not found
    Dependency '''org.deeplearning4j:deeplearning4j-core:0.5.1-SNAPSHOT''' not found

... in pom.xml.

changing that to 5.0 works but leads to errors elsewhere.

Any help would be appreciated.

Thanks,
  Andreas

**Comment by dandxy89** [comment]
I had the same issue, maybe @turambar can comment further. 

I did manage to build the project after modifying the pom file.

[POM file](https://gist.github.com/dandxy89/acf7caa1c080d5c131bb6749bc2631bb)

Hope that helps in the meantime

**Comment by turambar** [comment]
For the moment, ScalNet requires building DL4J from source, hence the reference to 0.5.1-SNAPSHOT. We're using some of the bleeding edge DL4J features, such as InputTypes. ScalNet will be a part of the next official release (0.6) at which point (I think) the version in the github repos will not require building from source. I'll leave this issue open until then.
